### PR TITLE
Compatibility with Plugin Loader

### PR DESCRIPTION
**Pull request by austinvaness**
Downgraded to C# 7.3 and removed some unused files in order to make the code compatible with Plugin Loader.

### CODE REVIEW

**Comment by viktor-ferenczi** [comment]
Reviewed the changes. They look good. 

I'm going to test the changes with a HP G2 HMD, can also test with Oculus Quest 2 shortly.

Also waiting on @Math0424 to approve this because of the language downgrade. 

I think getting a working VR plugin on Plugin Loader well worth this inconvenience. Hopefully we can get newer C# language version into SE in the future and the code can be upgraded again.

**Comment by viktor-ferenczi** [comment]
Upgrade LibHarmony package to 2.2.2 to be in sync with Plugin Loader

**Comment by austinvaness** [comment]
Harmony version updated.

**Comment by viktor-ferenczi** [comment]
Verified on HP G2 and Oculus (Meta) Quest 2. Both works fine.

**Pull request merged**
