### PR TITLE
Rebase of Plugin to PluginTemplate

### PR DESCRIPTION
**Pull request by WesternSpace**
- Replaced old logging system with new one.
- Replaced `SpaceVR.cs` with `Main.cs` due to major changes.
- Added feature to disable keyboard and mouse controls.
- Added feature to disable rendering of character (It disables rendering of all characters and changes to disable character rendering take effect after world reload. Proper implementation coming soon.)

### CODE REVIEW

**Comment by Math0424** [comment]
Going through the general code here are some of my comments:

CharacterRenderDisabler:
- If I'm reading this right this disables every character from rendering
- This doesn't need to be a patch, it is a component that's apart of the character, just remove the component
- This will also be replaced very soon as the character will be getting a new VR model

ICommonPlugin:
- whats the point of this? why does this exist? 

PatchHelpers:
- why does a class exist for 1 single method

PluginLogger:
- Why would I need to do Main.Instance.Log, why not just PluginLogger.Instance or even a static reference like PluginLogger.Log("message")

Common:
- You are setting the ICommonPlugin on init but almost each time you access logs you use Main.Instance
- Shouldn't stuff like the config name go here too, and not in Main

Main:
- this is a bit silly of a name
- Why would EnsureInitialized be called every update, just call it on init(), infact why not just call Initialize() on init()
- in Init() Dont patch the game if OpenVR isn't installed 
- Why does there need to be a CustomUpdate() just run the if statement in the Update() method and continue if it passed

**Comment by WesternSpace** [comment]
There are separate methods for `Update()` and `Init()` because there are exception wrappers around the actual `Update()` and `Init()` methods. I fixed the issue of patches running when you are not playing in VR. Viktor will explain to you about the `EnsureInitialized()` method.

**Comment by viktor-ferenczi** [comment]
`EnsureInitialized` is the error handling wrapper method over the one time initialization method `Initialize`.

The other seemingly unneeded classes are because of merging stuff from the PluginTemplate project, which supports 3 targets (client, DS, Torch). Certainly they can be simplified a lot, since we need to support only the client.

I actually suggested only to copy over the config dialog from the template.

Logging calls can be simplified because it needs to support only client logging.

I suggest doing the simplifications Math suggested wherever applicable and not removing error handling and logging, which may still be useful if something does not work.

**Comment by viktor-ferenczi** [comment]
> Why would EnsureInitialized be called every update?

That's because some initializations need the world to be completely loaded and already running. Also the time Init calls differs between client and server. Since the plugin template supports both it was solved this way.

Certainly we don't need it in this case, so we can just call Initialize from Init, indeed. I would still keep the try-catch with proper error logging.

**Comment by viktor-ferenczi** [comment]
> disables every character from rendering

Isn't that a bit overkill? It only needs to disable the player's own character rendering if it is in first person view. We should still be able to see the other characters.

**Pull request merged**
