### PR TITLE
Changes from Western.

### PR DESCRIPTION
**Pull request by WesternSpace**
Added detection if headset or controllers are disconnected during gameplay.
Code is untested due to me having no VR controllers and my phone VR setup.

### CODE REVIEW

**Comment by Math0424** [comment]
This would stop the rendering of the HMD if the controllers are disconnected? The current system also already supports hot-swapping controllers

**Comment by WesternSpace** [comment]
I made the message box for if a controller is disconnected pop up in the HMD instead. The message box that shows up on the desktop when the HMD is disconnected is now async.

**Comment by viktor-ferenczi** [comment]
Tested it. Game crashed on disconnecting the HMD. Logs sent to Western.

**Comment by WesternSpace** [comment]
Game crashing on HMD disconnection is unrelated to new code in this PR. This PR also includes code to resize the game resolution to normal on world unload for the desktop.

**Comment by WesternSpace** [comment]
Code now also disables mouse camera movement. Edit: It actually disables player movement also, but this should not matter as it does not impact VR controls.

**Comment by WesternSpace** [comment]
PR is broken, making a new one.

**Pull request closed without merging**
